name: flutter_nav_kit_example
description: Cold start â†’ login â†’ home â†’ FormPage for flutter_nav_kit.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  auto_route: ^11.1.0
  flutter:
    sdk: flutter
  flutter_app_kit:
    path: ../../flutter_app_kit
  lemsa_nav_kit:
    path: ../
  flutter_page_kit:
    path: ../../flutter_page_kit
  flutter_riverpod: ^3.4.2
  lemsa_core_kit:
    path: ../../lemsa_core_kit

dev_dependencies:
  auto_route_generator: ^10.6.0
  build_runner: ^2.16.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
